version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: "umidjon06"
      POSTGRES_DATABASE: umid
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
    ports:
      - 5435:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      DB_PASSWORD: "umidjon06"
      DB_DATABASE: postgres
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  db_data:
